#!/bin/bash
# SessionStart Hook - Runs when Claude Code session starts

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔒 Security Auditor Plugin v1.0.0 - Active"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📋 Available Security Tools:"
echo ""
echo "   Commands:"
echo "   • /security:audit           - Full security audit"
echo "   • /security:scan-deps       - Check dependencies"
echo "   • /security:check-secrets   - Find hardcoded secrets"
echo "   • /security:report          - Generate compliance report"
echo ""
echo "   Agents (call by name):"
echo "   • security-expert           - Code security review"
echo "   • compliance-checker        - Standards validation"
echo ""
echo "   Auto-Active Skills:"
echo "   • vulnerability-detection   - Real-time code scanning"
echo "   • dependency-analysis       - Package monitoring"
echo "   • code-scanning            - Malicious pattern detection"
echo ""
echo "💡 Quick Start:"
echo "   Run '/security:audit' before production deployment"
echo "   Minimum passing score: 85/100"
echo ""
echo "🔐 Pre-commit hook is active - secrets will be blocked automatically"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
