#!/bin/bash
# Security Report Generator

set -euo pipefail

FORMAT="${1:-markdown}"
TIMESTAMP=$(date +"%Y-%m-%d_%H-%M-%S")
REPORT_FILE="security-report-${TIMESTAMP}.${FORMAT}"
SCRIPT_DIR="$(dirname "$0")"

# Verify dependencies
if ! command -v bash >/dev/null 2>&1; then
    echo "❌ bash not found"
    exit 1
fi

echo "📄 Generating Security Report..."
echo "Format: ${FORMAT}"
echo "Output: ${REPORT_FILE}"
echo ""

# Create temp directory
TEMP_DIR=$(mktemp -d)
trap "rm -rf $TEMP_DIR" EXIT

# Run all scans and collect results (with error handling)
echo "🔍 Running comprehensive security audit..."
if bash "${SCRIPT_DIR}/audit.sh" > "${TEMP_DIR}/audit-results.txt" 2>&1; then
    echo "✅ Audit complete"
else
    echo "⚠️  Audit completed with warnings"
fi

echo "🔍 Scanning dependencies..."
if bash "${SCRIPT_DIR}/scan-dependencies.sh" > "${TEMP_DIR}/deps-results.txt" 2>&1; then
    echo "✅ Dependency scan complete"
else
    echo "⚠️  Dependency scan completed with warnings"
fi

echo "🔍 Checking for secrets..."
if bash "${SCRIPT_DIR}/check-secrets.sh" > "${TEMP_DIR}/secrets-results.txt" 2>&1; then
    echo "✅ Secret detection complete"
else
    echo "⚠️  Secret detection completed with warnings"
fi

echo ""
echo "📝 Generating report..."

# Generate report
cat > "$REPORT_FILE" << EOF
# Security Audit Report

**Generated:** $(date)
**Project:** $(basename "$(pwd)")
**Auditor:** Security Auditor v1.0.0
**Report ID:** ${TIMESTAMP}

---

## Executive Summary

$(grep "Security Score" "${TEMP_DIR}/audit-results.txt" 2>/dev/null || echo "Security Score: Pending Analysis")

$(grep -E "PASSED|WARNING|FAILED" "${TEMP_DIR}/audit-results.txt" 2>/dev/null || echo "Status: In Progress")

---

## Detailed Findings

### 1. General Security Audit

\`\`\`
$(cat "${TEMP_DIR}/audit-results.txt" 2>/dev/null || echo "Audit results not available")
\`\`\`

---

### 2. Dependency Analysis

\`\`\`
$(cat "${TEMP_DIR}/deps-results.txt" 2>/dev/null || echo "Dependency scan results not available")
\`\`\`

---

### 3. Secret Detection

\`\`\`
$(cat "${TEMP_DIR}/secrets-results.txt" 2>/dev/null || echo "Secret detection results not available")
\`\`\`

---

## Recommendations

### Critical Actions
1. **Address all critical security findings immediately**
2. **Fix dependency vulnerabilities** - Update all packages with known CVEs
3. **Remove hardcoded secrets** - Use environment variables or secret management

### High Priority
1. **Implement input validation** - Prevent injection attacks
2. **Enable security headers** - HTTPS, CSP, X-Frame-Options
3. **Configure logging** - Track security events

### Medium Priority
1. **Update outdated dependencies** - Stay current with security patches
2. **Conduct code review** - Security-focused review before deployment
3. **Add automated scanning** - Integrate into CI/CD pipeline

---

## Compliance Checklist

Security Standards:
- [ ] OWASP Top 10 vulnerabilities addressed
- [ ] CWE Top 25 weaknesses mitigated
- [ ] All dependencies up-to-date and secure

Secure Development:
- [ ] No hardcoded secrets or credentials
- [ ] Proper input validation and sanitization
- [ ] Secure authentication and authorization
- [ ] HTTPS/TLS properly configured

Operations:
- [ ] Security headers configured
- [ ] Logging and monitoring in place
- [ ] Incident response plan documented
- [ ] Regular security updates scheduled

---

## Sign-Off

**Security Review Required:** YES
**Deployment Approved:** PENDING

**Next Steps:**
1. Review this report with security team
2. Address all critical and high-priority issues
3. Re-run security audit after fixes
4. Obtain formal approval before production deployment

---

**Report Generated By:** Security Auditor Plugin v1.0.0
**Contact:** Security Team
**Valid Until:** $(date -v+30d '+%Y-%m-%d' 2>/dev/null || date -d '+30 days' '+%Y-%m-%d' 2>/dev/null || date '+%Y-%m-%d')

---

*This is an automated security report. Manual review recommended.*
EOF

echo "✅ Report generated successfully!"
echo ""
echo "📄 Report saved to: ${REPORT_FILE}"
echo ""
echo "Preview:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
head -50 "$REPORT_FILE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "💡 Tip: Open ${REPORT_FILE} in your editor for full report"
